drop table traffic_lights;
create table traffic_lights
(
    id          NUMBER GENERATED BY DEFAULT AS IDENTITY,
    car_id      varchar2(100)                          not null,
    arrived     date                                   not null,
    crossed     date                                   not null,
    source      varchar2(100)                          not null,
    destination varchar2(100)                          not null,
    violator    CHAR(1) check (violator in ('N', 'Y')) not null,

    CONSTRAINT traffic_lights_pk PRIMARY KEY (id)
);
commit;
create index traffic_lights_date_event on traffic_lights (crossed, violator);

truncate table traffic_lights;

commit;

select count(*)
from traffic_lights;

select *
from traffic_lights
where violator = 'Y';

select *
from traffic_lights;

truncate table traffic_lights;